---
- hosts: dbserver 
  vars:
    tailscale_apt_keyring_path: /usr/share/keyrings/tailscale-archive-keyring.gpg
    tailscale_apt_deb: deb [signed-by={{ tailscale_apt_keyring_path }}] https://pkgs.tailscale.com/stable/ubuntu {{ ansible_distribution_release | lower }} main
    tailscale_apt_signkey: https://pkgs.tailscale.com/stable/ubuntu/{{ ansible_distribution_release | lower }}.noarmor.gpg

    postgres_version: 15
    ubuntu_distro: focal #this needs to match lsb_release -cs command output

  become: yes
  tasks:
    - name: Perform Safe Upgrade
      apt: upgrade=safe update_cache=yes

    - name: Install Server Basics
      apt: pkg={{ item }} state=present update_cache=true
      with_items:
        - unattended-upgrades
        - ntp
        - wget
        - curl
      notify:
        - Start NTP

    - name: Install tailscale deps
      apt: pkg={{ item }} state=present update_cache=true
      with_items:
        - gnupg2
        - gnupg-agent
        - apt-transport-https
        - python3-apt

    - name: Add Tailscale Signing Key
      become: true
      ansible.builtin.get_url:
        dest: "{{ tailscale_apt_keyring_path }}"
        url: "{{ tailscale_apt_signkey }}"
        mode: '0644'

    - name: Add Tailscale Deb
      become: true
      ansible.builtin.apt_repository:
        repo: "{{ tailscale_apt_deb }}"
        state: present

    - name: Install Tailscale
      become: true
      ansible.builtin.apt:
        name: "tailscale"
        cache_valid_time: 3600
        state: 'latest'
      notify:
        - enable tailscale
        - restart tailscale

    - name: Install Qemu Guest Package
      ansible.builtin.apt:
        name:
          - qemu-guest-agent
        update_cache: yes
        state: latest
      when: ansible_system_vendor == 'QEMU'
      notify:
        - enable Qemu Agent
        - restart Qemu Agent

    - name: Add Periodic Configuration
      copy: src=files/dbserver/10periodic dest=/etc/apt/apt.conf.d/10periodic owner=root group=root

    - name: Add Unattended Upgrade Configuration
      copy: src=files/dbserver/50unattended-upgrades dest=/etc/apt/apt.conf.d/50unattended-upgrades owner=root group=root
      notify:
      - Restart Unattended Upgrades

    # For details see https://wiki.postgresql.org/wiki/Apt
    - name: Add Postgres Apt Key
      become: true
      ansible.builtin.apt_key: 
        url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
        state: present

    - name: Add Postgres Repo
      become: true
      ansible.builtin.apt_repository: 
        repo: 'deb http://apt.postgresql.org/pub/repos/apt/ {{ ubuntu_distro }}-pgdg main'
        state: present

    - name: Install Postgres
      ansible.builtin.apt:
        name:
          - postgresql-{{ postgres_version }}
          - libpq-dev
          - postgresql-contrib-{{ postgres_version }}
        update_cache: yes
        state: latest
      notify:
        - enable postgresql
        - restart postgresql

    - name: Add postgres hba conf
      become: true
      copy: src=files/dbserver/postgres/postgres_config/main/pg_hba.conf dest=/etc/postgresql/15/main/pg_hba.conf owner=postgres group=postgres
      notify:
        - restart postgresql

    - name: Add postgres conf
      become: true
      copy: src=files/dbserver/postgres/postgres_config/main/postgresql.conf dest=/etc/postgresql/15/main/postgresql.conf owner=postgres group=postgres
      notify:
        - restart postgresql

  handlers:
    - name: restart Qemu Agent
      ansible.builtin.service:
        name: qemu-guest-agent
        state: restarted

    - name: enable Qemu Agent
      ansible.builtin.service:
        name: qemu-guest-agent
        enabled: true

    - name: Start NTP
      service: name=ntp state=started enabled=yes

    - name: Restart Unattended Upgrades
      service: name=unattended-upgrades state=restarted enabled=yes

    - name: enable tailscale
      ansible.builtin.service:
        name: tailscaled
        enabled: true

    - name: restart tailscale
      ansible.builtin.service:
        name: tailscaled
        state: restarted

    - name: enable postgresql
      ansible.builtin.service:
        name: postgresql@{{ postgres_version }}-main
        enabled: true

    - name: restart postgresql
      ansible.builtin.service:
        name: postgresql@{{ postgres_version }}-main
        state: restarted
