---
- name: enable postgresql
  ansible.builtin.service:
    name: postgresql@{{ postgres_version }}-main
    enabled: true

- name: restart postgresql
  ansible.builtin.service:
    name: postgresql@{{ postgres_version }}-main
    state: restarted
