---
- name: restart Qemu Agent
  ansible.builtin.service:
    name: qemu-guest-agent
    state: restarted

- name: enable Qemu Agent
  ansible.builtin.service:
    name: qemu-guest-agent
    enabled: true

- name: Start Timesyncd
  service: name=systemd-timesyncd state=started enabled=yes

- name: Start Unattended Upgrades
  service: name=unattended-upgrades state=started enabled=yes

- name: Restart Unattended Upgrades
  service: name=unattended-upgrades state=restarted enabled=yes

- name: enable tailscale
  ansible.builtin.service:
    name: tailscaled
    enabled: true

- name: restart tailscale
  ansible.builtin.service:
    name: tailscaled
    state: restarted

- name: Fetch Tailscale status
  listen: Confirm Tailscale is Connected
  ansible.builtin.command: tailscale status --json
  changed_when: false
  register: tailscale_status

- name: Parse status JSON
  listen: Confirm Tailscale is Connected
  vars:
    status: "{{ tailscale_status.stdout | from_json }}"
  ansible.builtin.set_fact:
    tailscale_is_online: "{{ status.Self.Online }}"

- name: Tailscale online status
  listen: Confirm Tailscale is Connected
  ansible.builtin.debug:
    msg: "Online: {{ tailscale_is_online }}"
  when: verbose

- name: Assert Tailscale is Connected
  listen: Confirm Tailscale is Connected
  ansible.builtin.assert:
    that:
      - tailscale_is_online
