# - name: Load Common Vars
#   vars:
#     params:
#       files:
#         - main.yml
#     paths:
#       - 'vars'

- name: Install Server Basics
  apt: pkg={{ item }} state=present update_cache=true
  with_items:
    - unattended-upgrades
    - systemd-timesyncd
    - wget
    - curl
  notify:
    - Start Timesyncd
    - Start Unattended Upgrades

- name: Turn on ntp
  command: /usr/bin/timedatectl set-ntp on

- name: Install tailscale deps
  apt: pkg={{ item }} state=present update_cache=true
  with_items:
    - gnupg2
    - gnupg-agent
    - apt-transport-https
    - python3-apt

- name: Add Tailscale Signing Key
  become: true
  ansible.builtin.get_url:
    dest: "{{ tailscale_apt_keyring_path }}"
    url: "{{ tailscale_apt_signkey }}"
    mode: '0644'

- name: Add Tailscale Deb
  become: true
  ansible.builtin.apt_repository:
    repo: "{{ tailscale_apt_deb }}"
    state: present

- name: Install Tailscale
  become: true
  ansible.builtin.apt:
    name: "tailscale"
    cache_valid_time: 3600
    state: 'latest'
  notify:
    - enable tailscale
    - restart tailscale

- name: Install Qemu Guest Package
  ansible.builtin.apt:
    name:
      - qemu-guest-agent
    update_cache: yes
    state: latest
  when: ansible_system_vendor == 'QEMU'
  notify:
    - enable Qemu Agent
    - restart Qemu Agent

- name: Add Periodic Configuration
  copy: src=files/10periodic dest=/etc/apt/apt.conf.d/10periodic owner=root group=root

- name: Add Unattended Upgrade Configuration
  copy: src=files/50unattended-upgrades dest=/etc/apt/apt.conf.d/50unattended-upgrades owner=root group=root
  notify:
  - Restart Unattended Upgrades

